# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/TOP_PIN.xdc

# IP: ip/aurora_64b66b_0/aurora_64b66b_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==aurora_64b66b_0 || ORIG_REF_NAME==aurora_64b66b_0} -quiet] -quiet

# XDC: ip/aurora_64b66b_0/aurora_64b66b_0_ooc.xdc

# XDC: ip/aurora_64b66b_0/aurora_64b66b_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0 || ORIG_REF_NAME==aurora_64b66b_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/aurora_64b66b_0/aurora_64b66b_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==aurora_64b66b_0 || ORIG_REF_NAME==aurora_64b66b_0} -quiet] {/inst } ]/inst ] -quiet] -quiet
